# -*- coding: utf-8 -*-
"""list_dict_extend_df.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOO6W2ed6ULq_Rtv7Gv64CeKYfxjIUFM
"""

# create an empty list
my_list = []

# create a dictionary
my_dict = {
    'name' : 'John',
    'age' : 30,
    'city' : 'New York'
}

# append the dictionary to the list
my_list.append(my_dict)

# print the list
print(my_list)

# create another dictionary
my_dict2 = {
    'name' : 'Jane',
    'age' : 25,
    'city' : 'London'
}

# append the new dictionary to the list
my_list.append(my_dict2)

# print the updated list
print(my_list)

my_new_list = []                                                # create an empty list

my_new_dict = {'name':'bob', 'age':20, 'city':'paris'}          # create dictionaries
my_dict_2 = {'name':'alice', 'age':25, 'city':'london'}
my_dict_3 = {'name':'charlie', 'age':30, 'city':'berlin'}
my_dict_4 = {'name':'david', 'age':35, 'city':'madrid'}

my_new_list.append(my_new_dict)                                 # append the dictionaries to the list
my_new_list.append(my_dict_2)
my_new_list.append(my_dict_3)
my_new_list.append(my_dict_4)

print(my_new_list)                                               # print the list

import pandas as pd                                               # create dataframe for the list

df = pd.DataFrame(my_new_list)
print(df)

my_list1 = []                                                 # create an empty list

new_dictionaries = [                                          # create dictionaries in a list
    {'name':'bob', 'age':20, 'city':'paris'},
    {'name':'alice', 'age':25, 'city':'london'},
    {'name':'charlie', 'age':30, 'city':'berlin'}
]

my_list1.extend(new_dictionaries)                              # add dictionaries to the list using extend method

print(my_list1)                                                # print the list

df1 = pd.DataFrame(my_list1)                                   # create dataframe for the list
print(df1)